"""Public API for the AegisAl plugin runtime."""

from .context import PluginContext
from .effects import EffectHandle, EffectScope
from .errors import (
    DrainTimeoutError,
    EffectCleanupError,
    EffectScopeClosedError,
    ManifestError,
    PluginActivationError,
    PluginDependencyError,
    PluginNotFoundError,
    PluginRuntimeError,
    PluginSecurityError,
    PluginStateError,
    RegistryConflictError,
    RegistryError,
    RegistryKeyError,
)
from .models import (
    PLUGIN_SCHEMA_VERSION,
    ExecutionMode,
    PluginDependency,
    PluginManifest,
    PluginSnapshot,
    PluginState,
    TrustLevel,
)
from .registry import (
    EXECUTABLE_REGISTRIES,
    ReadOnlyRegistry,
    RegistrationHandle,
    RegistrationMetadata,
    RegistrationOwner,
    Registry,
    RegistryEntry,
    RegistryHub,
    StagedRegistration,
)
from .runtime import (
    DeclarativeContribution,
    DeclarativePlugin,
    GenerationLease,
    GenerationSnapshot,
    PluginActivator,
    PluginManager,
)

__all__ = [
    "PLUGIN_SCHEMA_VERSION",
    "EXECUTABLE_REGISTRIES",
    "DeclarativeContribution",
    "DeclarativePlugin",
    "DrainTimeoutError",
    "EffectCleanupError",
    "EffectHandle",
    "EffectScope",
    "EffectScopeClosedError",
    "ExecutionMode",
    "GenerationLease",
    "GenerationSnapshot",
    "ManifestError",
    "PluginActivationError",
    "PluginActivator",
    "PluginContext",
    "PluginDependency",
    "PluginDependencyError",
    "PluginManager",
    "PluginManifest",
    "PluginNotFoundError",
    "PluginRuntimeError",
    "PluginSecurityError",
    "PluginSnapshot",
    "PluginState",
    "PluginStateError",
    "ReadOnlyRegistry",
    "RegistrationHandle",
    "RegistrationMetadata",
    "RegistrationOwner",
    "Registry",
    "RegistryConflictError",
    "RegistryEntry",
    "RegistryError",
    "RegistryHub",
    "RegistryKeyError",
    "StagedRegistration",
    "TrustLevel",
]
